---
- name: Stat the final device file
  include_tasks: stat_device.yml

- name: Remove file system as needed
  shell: wipefs {{ fs_destroy_options }} {{ device_path }}
  when: fs_type == "" or state == "absent" and device_status.stat.exists

- name: Create filesystem as needed
  filesystem:
    dev: "{{ device_path }}"
    fstype: "{{ fs_type }}"
    opts: "{{ fs_create_options }}"
  when: fs_type != "" and state == "present" and device_status.stat.exists
