---
- name: Stat the final device file
  include_tasks: stat_device.yml

- name: Install xfsprogs for xfs file system type
  package:
    name: xfsprogs
    state: present
  when: volume.fs_type == "xfs" and not ansible_check_mode

- name: Install e2fsprogs for ext file system type
  package:
    name: e2fsprogs
    state: present
  when: volume.fs_type in ["ext2", "ext3", "ext4"]

- name: Install util-linux as needed
  package:
    name: util-linux
    state: present
  when: volume.fs_type == "swap" or volume.state == "absent"

- name: Remove file system as needed
  command: wipefs {{ volume.fs_destroy_options }} {{ device_path }}
  when: (not volume.fs_type or volume.state == "absent") and device_status.stat.exists and not ansible_check_mode

- name: Create filesystem as needed
  filesystem:
    dev: "{{ device_path }}"
    fstype: "{{ volume.fs_type }}"
    opts: "{{ volume.fs_create_options }}"
  when: volume.fs_type and volume.state == "present" and device_status.stat.exists
