---
- name: Install LVM2 commands as needed
  package:
    name: lvm2
    state: present
  when: volume.type == "lvm"

- name: Make sure LV exists
  lvol:
    lv: "{{ volume.name }}"
    vg: "{{ pool.name }}"
    size: "{{ size.lvm }}"
    state: "{{ volume.state if pool.state != 'absent' else pool.state }}"
    force: yes
    shrink: no
  when: volume.type == "lvm" and pool.name
