---
- name: Install LVM2 commands as needed
  package:
    name: lvm2
    state: present
  when: volume.type == "lvm"

- name: Make sure LV exists
  lvol:
    lv: "{{ volume.name }}"
    vg: "{{ volume.pool_name }}"
    size: "{{ size.lvm }}"
    state: "{{ volume.state }}"
    force: yes
    shrink: no
  when: volume.type == "lvm" and volume.pool_name
