---
- name: Install LVM2 commands as needed
  package:
    name: lvm2
    state: present
  when: volume_type == "lvm"

- name: Make sure LV exists
  lvol:
    lv: "{{ volume_name }}"
    vg: "{{ pool_name }}"
    size: "{{ parsed_size.lvm }}"
    state: "{{ state }}"
    force: yes
    shrink: no
  when: volume_type == "lvm" and pool_name
