---
- name: define an empty list of pools to be used in testing
  set_fact:
    _storage_pools_list: []

- name: define an empty list of volumes to be used in testing
  set_fact:
    _storage_volumes_list: []

- name: include the appropriate backend tasks
  include_tasks: "main-{{ storage_backend }}.yml"
