---

- name: manage a partition
  parted:
    device: "{{ part_info.disk }}"
    label: "{{ part_info.disklabel }}"
    number: "{{ part_info.number }}"
    name: "{{ part_info.name }}"
    state: "{{ part_info.state }}"
  when: part_info is defined and part_info
